services:
  distcc:
    build:
      context: .
      dockerfile: Arch.Dockerfile
    container_name: distcc-worker
    ports:
      - "3632:3632"
    environment:
      DISTCC_LOG: /tmp/distcc.log
      DISTCC_VERBOSE: "1"
      DISTCC_SAVE_TEMPS: "0" # The error files are deleted on the server, but they should be available for the client to see shortly before exiting
      # In the rare case where errors literally differ from server and client, use this
    command: >
      sh -c "
      distccd
      --daemon
      --no-detach
      --verbose
      --allow 192.168.0.0/16
      --allow 172.16.0.0/16
      --jobs $(nproc)
      --log-stderr
      "
